DROP TABLE IF EXISTS stats;

CREATE TABLE stats (
    stats_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    app varchar(100) NOT NULL,
    uri varchar(100) NOT NULL,
    ip varchar(100) NOT NULL,
    timestamp timestamp with time zone NOT NULL
);